name: High Seas Web CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: node:18.18-alpine3.18

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file web/Dockerfile --tag high-seas-web:$(date +%s)
